const userTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  REGISTER_USER_ERROR: "REGISTER_USER_ERROR",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  RESET_USER_SUCCESS: "RESET_USER_SUCCESS",
  RESET_USER_ERROR: "RESET_USER_ERROR",
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
};
export default userTypes;
