const userTypes = {
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_USER_START: "SIGN_OUT_USER_START",
  SIGN_OUT_USER_SUCCESS: "SIGN_OUT_USER_SUCCESS",
  SIGN_UP_USER_START: "SIGN_UP_USER_START",
  SIGN_UP_USER_SUCCESS: "SIGN_UP_USER_SUCCESS",
  SIGN_UP_USER_ERROR: "SIGN_UP_USER_ERROR",

  SET_CURRENT_USER: "SET_CURRENT_USER",
  REGISTER_USER_ERROR: "REGISTER_USER_ERROR",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  RESET_USER_SUCCESS: "RESET_USER_SUCCESS",
  RESET_USER_ERROR: "RESET_USER_ERROR",
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
};
export default userTypes;
