const categoryTypes = {
  ADD_CATEGORY_START: "ADD_CATEGORY_START",
  FETCH_CATEGORIES_START: "FETCH_CATEGORIES_START",
  SET_CATEGORIES: "SET_CATEGORIES",
  DELETE_CATEGORY_START: "DELETE_CATEGORY_START",
};

export default categoryTypes;
